In [1]:
import tensorflow as tf
import numpy as np

tf.InteractiveSession()

ones = tf.ones((3,4,2))
print(ones)

Tensor("ones:0", shape=(3, 4, 2), dtype=float32)


In [2]:
ones.eval()

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)

In [3]:
print(tf.ones(1))

Tensor("ones_1:0", shape=(1,), dtype=float32)


In [4]:
print(tf.ones(1).eval())

[1.]


In [5]:
fill_in_tensor = tf.fill((2,2), 4)
print(fill_in_tensor)

Tensor("Fill:0", shape=(2, 2), dtype=int32)


In [6]:
print(fill_in_tensor.eval())

[[4 4]
 [4 4]]


tf.constant is another function, similar to tf.fill which allows for construction of Tensors which shouldn’t change during the program execution.

In [7]:
const = tf.constant(3)
const.eval()

3

In [8]:
randomised_tf = tf.random_normal((2,3), mean = 10, stddev = 2)
randomised_tf.eval()

array([[ 8.54633  , 12.953601 , 10.97482  ],
       [ 9.44176  , 13.749488 ,  7.8798647]], dtype=float32)

Here you can notice that values that are shufled do not correspond with values randomised_tf. Every Tensor is a function how to obtain values. For example a constant means a function thta provide a constant, a random_normal tensor means a tensor that at every evaluation will give you random values 

In [9]:
shufled_rand = tf.random_shuffle(randomised_tf)
shufled_rand.eval()

array([[ 9.66626 , 10.268268,  9.879948],
       [ 8.949551,  9.998351,  9.376   ]], dtype=float32)

In [10]:
shufled_rand.eval()

array([[10.793601 , 11.196882 , 12.65596  ],
       [10.757628 , 11.260205 ,  9.2112665]], dtype=float32)

In [11]:
shufled_rand.eval()

array([[12.090835 , 11.642128 ,  7.7503214],
       [11.633049 , 11.027738 ,  8.381154 ]], dtype=float32)

In [12]:
randomised_uniformly_tf = tf.random_uniform((2, 2), minval = 8, maxval = 12)
randomised_uniformly_tf.eval()

array([[ 9.302863,  8.938329],
       [11.739334,  9.570727]], dtype=float32)

In [13]:
a = tf.ones((3,3))
b = tf.fill((3,3), 5.)
c = a + b
d = c*2
d.eval()

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]], dtype=float32)

In [14]:
eye_tf = tf.eye(3)
eye_tf.eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [15]:
r = tf.range(1,10,2)
r.eval()

array([1, 3, 5, 7, 9], dtype=int32)

In [16]:
diag = tf.diag(r)
diag.eval()

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]], dtype=int32)

In [17]:
transposed_ones = tf.matrix_transpose(ones[0])
transposed_ones.eval()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [18]:
multiplied = tf.matmul(transposed_ones, ones[0])
multiplied.eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [19]:
tf.to_int32(multiplied).eval()

array([[4, 4],
       [4, 4]], dtype=int32)