In [1]:
import tensorflow as tf

tf.InteractiveSession()

ones = tf.ones((8))
print(ones)
ones.eval()

Tensor("ones:0", shape=(8,), dtype=float32)


array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [2]:
reshaped_ones = tf.reshape(ones, (4,2))
print(reshaped_ones)
reshaped_ones.eval()

Tensor("Reshape:0", shape=(4, 2), dtype=float32)


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [4]:
reshaped_3d_ones = tf.reshape(ones, (2,2,2))
print(reshaped_3d_ones)
reshaped_3d_ones.eval()

Tensor("Reshape_1:0", shape=(2, 2, 2), dtype=float32)


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [10]:
expanded_tf = tf.expand_dims(reshaped_3d_ones, axis = 2)
print(expanded_tf)
expanded_tf.eval()

Tensor("ExpandDims_5:0", shape=(2, 2, 1, 2), dtype=float32)


array([[[[1., 1.]],

        [[1., 1.]]],


       [[[1., 1.]],

        [[1., 1.]]]], dtype=float32)

In [20]:
print(expanded_tf[0][0].eval())
print(expanded_tf[0][0][0].eval())

[[1. 1.]]
[1. 1.]


In [29]:
squeezed_tf = tf.squeeze(reshaped_3d_ones)
print(squeezed_tf)
squeezed_tf.eval()

Tensor("Squeeze_8:0", shape=(2, 2, 2), dtype=float32)


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [31]:
double_squeezed_tf = tf.squeeze(squeezed_tf)
print(double_squeezed_tf)
double_squeezed_tf.eval()

Tensor("Squeeze_10:0", shape=(2, 2, 2), dtype=float32)


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [32]:
ones.get_shape()

TensorShape([Dimension(8)])

In [33]:
reshaped_3d_ones.get_shape()

TensorShape([Dimension(2), Dimension(2), Dimension(2)])