In [1]:
import tensorflow as tf

sess = tf.Session()
a = tf.ones((3,3))
b = tf.matmul(a, a)
b.eval(session = sess)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [2]:
sess.run(b)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [3]:
a_variable = tf.Variable(tf.ones((3,3)))
print(a_variable)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32_ref>


In [4]:
# The command bellow will fail because of unintialised varriable a_variable
#sess.run(a_variable)

In [5]:
sess.run(tf.global_variables_initializer())
sess.run(a_variable)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [7]:
sess.run(a_variable.assign(tf.zeros((3,3))))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [8]:
sess.run(a_variable)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [9]:
#Placeholder example

a = tf.placeholder(tf.float32, shape=[1])
v = tf.placeholder(tf.float32, shape=[1])
b = tf.multiply(a, v)

sess = tf.Session()
model = tf.global_variables_initializer()

sess.run(model)

print(sess.run(b,feed_dict={a: (4,), v:(5,)}))

[20.]
